// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { Pool } from "pg"; // or the appropriate adapter for PostgreSQL

const databaseUrl = process.env["DATABASE_URL"];

const pool = new Pool({ connectionString: databaseUrl });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    adapter: pool,
  },
});
