// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local", override: true });
config();
import { defineConfig } from "prisma/config";

// Use pooler URL for application queries
const databaseUrl = process.env["DATABASE_URL"];
// Use direct URL for migrations (bypasses pooler for faster schema changes)
const directUrl = process.env["DIRECT_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // directUrl bypasses pgbouncer/pooler for migrations - much faster
    url: directUrl || databaseUrl,
  },
});
